### ISSUE TITLE
Cannot pip install the microstructpy when process bug at matplotlib installation

### ISSUE THREAD

**Issue by PikaPika141** [kip-hart/MicroStructPy#19] opened 2020-05-27 09:18 UTC
When I try to install the microstuctpy I found that there is a problem when matplotlib content is installing within the whole installation of microstructpy.
![error](https://user-images.githubusercontent.com/66006994/83001092-d5e18f80-a03d-11ea-9e85-c3ee55d2dae5.png)

Before that I have installed scipy and numpy in this new-build conda environment. necessary c++ development enviro have been installed

When I try to solve this I found that all discussion only talk about several special version matplotlib installation. For this case there is no discussion.

How can I solve that?

**Comment by kip-hart** [comment] 2020-05-27 15:14
Sorry to hear you are having issues with installing the package - it looks like the issue is with matplotlib. I made the requirements for installation `matplotlib<3.1.0,>=2.2.0` because there are some unresolved problems with 3D plotting.

I recommend installing matplotlib in the environment first, then microstructpy. For instance,

```bash
pip install matplotlib
```

If this does not work, then my guess is there is an issue with anaconda's environment. Based on the error message,  it seems like there are missing links to the `freetype` and `png` C/C++ headers. I can't really help with anaconda errors since I use `virtualenv` to create environments. Something like this would create an environment:

```bash
pip install virtualenv
python -m virtualenv mesh2
source mesh2/bin/activate
```

Let me know what you find - I'd like to help resolve this issue with installation.

**Comment by PikaPika141** [comment] 2020-05-31 04:09
I try to intall it on ubunto env. Finally and fortuantely it works!
Although I cannot on-time run it in pycharm but I can save the .py file and then run it in jupyter lab or powershell cmd (Win10).
Is the txt file or vtk content format readable for Ansys? 
I am using this pack as geometry support for my master project

**Comment by kip-hart** [comment] 2020-05-31 05:46
Glad to hear that it's installed and you're generating files! Currently the output file types are limited, but the plan is to eventually inherit from the meshio mesh class because it can write to so many file types.

That won't happen for several months though, since I'm trying to finish my thesis at the moment. If the need is urgent, I'd recommend creating an ANSYS file writer script - using the source code for TriMesh.write as a guide.

**Comment by PikaPika141** [comment] 2020-05-31 08:55
Thanks for that！

**Comment by kip-hart** [comment] 2020-05-31 16:21
Closing this for now - feel free to reopen if there's another issue with installation. Best of luck on your masters project.

**Closed by kip-hart** 2020-05-31 16:21 UTC
